name: performance_interceptor
description: Intereceptors for Firebase peformance http Metric.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_performance: ^0.7.0+5

  http_interceptor: ^1.0.0
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: